services:
  postgres:
    image: postgres:16
    container_name: cruz_azul_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cruzazul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  postgres_data:
